// <auto-generated />
namespace HeroProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class second_mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(second_mig));
        
        string IMigrationMetadata.Id
        {
            get { return "202301091343501_second_mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
